"""QC report generation and hard-gate helpers."""

from __future__ import annotations

import csv
import json
from dataclasses import asdict
from pathlib import Path
from typing import Iterable

import numpy as np

from skin_optics_so1.synthetic_manifest import ManifestRow


def pearson(x: np.ndarray, y: np.ndarray) -> float:
    if x.size < 2 or float(np.std(x)) == 0.0 or float(np.std(y)) == 0.0:
        return float("nan")
    return float(np.corrcoef(x, y)[0, 1])


def _spearman(x: np.ndarray, y: np.ndarray) -> float:
    rx = np.argsort(np.argsort(x))
    ry = np.argsort(np.argsort(y))
    return pearson(rx.astype(np.float64), ry.astype(np.float64))


def write_preview_png(path: str | Path, linear_rgb_chw: np.ndarray) -> None:
    try:
        from PIL import Image
    except Exception:
        return
    x = np.clip(linear_rgb_chw.transpose(1, 2, 0), 0, 1)
    # This preview is only for visual QC; gamma encode for display.
    srgb = np.where(x <= 0.0031308, 12.92 * x, 1.055 * np.power(np.clip(x, 0.0031308, 1), 1 / 2.4) - 0.055)
    img = (np.clip(srgb, 0, 1) * 255).astype(np.uint8)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(img, mode="RGB").save(path)


def summarize_manifest(rows: Iterable[ManifestRow]) -> dict:
    rows = list(rows)
    split_counts: dict[str, int] = {}
    pair_counts: dict[str, dict[str, int]] = {}
    for r in rows:
        split_counts[r.split] = split_counts.get(r.split, 0) + 1
        pair_counts.setdefault(r.split, {})
        pair_counts[r.split][r.camera_light_pair] = pair_counts[r.split].get(r.camera_light_pair, 0) + 1
    m_means = np.asarray([r.m_mean for r in rows if np.isfinite(r.m_mean)], dtype=np.float64)
    h_means = np.asarray([r.h_mean for r in rows if np.isfinite(r.h_mean)], dtype=np.float64)
    return {
        "total_rows": len(rows),
        "split_counts": split_counts,
        "success_count": sum(1 for r in rows if r.generation_status == "SUCCESS"),
        "failed_count": sum(1 for r in rows if r.generation_status == "FAILED"),
        "pending_count": sum(1 for r in rows if r.generation_status == "PENDING"),
        "mh_mean_pearson": pearson(m_means, h_means) if len(m_means) == len(h_means) else float("nan"),
        "mh_mean_spearman": _spearman(m_means, h_means) if len(m_means) == len(h_means) else float("nan"),
        "pair_counts": pair_counts,
    }


def write_qc_outputs(output_root: str | Path, rows: list[ManifestRow], smoke: bool = False, timing: dict | None = None) -> None:
    root = Path(output_root)
    root.mkdir(parents=True, exist_ok=True)
    stats = summarize_manifest(rows)
    stats["smoke"] = smoke
    stats["timing"] = timing or {}
    (root / "dataset_statistics.json").write_text(json.dumps(stats, indent=2, sort_keys=True, allow_nan=True) + "\n", encoding="utf-8")

    with (root / "pair_coverage.csv").open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["split", "camera_light_pair", "count"])
        writer.writeheader()
        for split, counts in sorted(stats["pair_counts"].items()):
            for pair, count in sorted(counts.items()):
                writer.writerow({"split": split, "camera_light_pair": pair, "count": count})

    clip_fields = ["sample_id", "split", "camera_light_pair", "low_clip_fraction", "high_clip_fraction", "total_clip_fraction", "per_channel_clip_fraction"]
    with (root / "clipping_statistics.csv").open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=clip_fields)
        writer.writeheader()
        for r in rows:
            writer.writerow({k: getattr(r, k) for k in clip_fields})

    report = [
        "# SO1 Synthetic Generation QC Report",
        "",
        f"- smoke: {smoke}",
        f"- total_rows: {stats['total_rows']}",
        f"- success_count: {stats['success_count']}",
        f"- failed_count: {stats['failed_count']}",
        f"- pending_count: {stats['pending_count']}",
        f"- M/H sample mean Pearson: {stats['mh_mean_pearson']}",
        f"- M/H sample mean Spearman: {stats['mh_mean_spearman']}",
        "",
        "This report is generated by SO-1 code without modifying SO-0 frozen assets.",
    ]
    (root / "synthetic_generation_qc_report.md").write_text("\n".join(report) + "\n", encoding="utf-8")


def rows_as_dicts(rows: list[ManifestRow]) -> list[dict]:
    return [asdict(r) for r in rows]
