experiment:
  name: R3DPR_ResNet34_ControlVsPatient_Binary_224x224_manual_shift_eye_roi_fullbaseline_ls005_5fold
  output_dir: experiments/500Data/R3DPR_ResNet34_ControlVsPatient_Binary_224x224_manual_shift_eye_roi_fullbaseline_ls005_5fold

task:
  type: binary_control_vs_patient
  num_classes: 2
  negative_class: control
  positive_class: patient

data:
  table_csv: data/processed/global_face_R3DPR/nyha_2class_sex_stratified_group_5fold.csv
  image_root: data/processed/roi_dataset/manual_shift_data/eye_roi
  image_filename_template: "{ID}.png"
  id_column: ID
  group_id_column: patient_group_id
  fold_column: fold
  label_column: binary_label
  sex_column: SEX
  n_folds: 5
  source_image_height: 224
  source_image_width: 224
  image_height: 224
  image_width: 224

model:
  backbone: resnet34
  pretrained: imagenet
  num_classes: 2
  trainability_strategy: full_finetune

train:
  batch_size: 16
  epochs: 50
  optimizer: AdamW
  lr: 0.0001
  weight_decay: 0.0001
  loss: weighted_ce_label_smoothing
  label_smoothing_alpha: 0.05
  early_stopping_patience: 10
  monitor_metric: macro_auc
  random_seed: 2026
  num_workers: 0
  pin_memory: true

augmentation:
  horizontal_flip: true

normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
