"""C1 completion: independent mask and compact-runtime audit (AUDIT_ONLY)."""
from __future__ import annotations
import hashlib,json,os,platform,sys,time
from pathlib import Path
import numpy as np,pandas as pd,yaml
from scipy import ndimage
from .paired_pilot import _so0,_matrix,_field,_appearance,_seed,_inputs,_schedule,_domain,_sha
def H(p): return _sha(p)
def main(root:Path):
 c=yaml.safe_load((root/'config/so_r1/so_r1_a2_p0_c1_completion_v1.yaml').read_text());out=root/c['output_root'];rep=root/c['report_root'];out.mkdir(parents=True,exist_ok=True);rep.mkdir(parents=True,exist_ok=True)
 # full protected ledger, excluding C1 itself
 targets=[root/'src/skin_optics_so0',root/'data/external/SO0_Spectral_Assets_v1',root/'outputs/SO0_Forward_Model_v1.1',root/c['frozen_split'],root/'reports/so_r1_a0_camera_light_selection',root/c['a1_root'],root/'reports/so_r1_a1_paired_pilot',root/c['p0_root'],root/'reports/so_r1_a2_p0_prefreeze_audit']; rows=[]
 for t in targets:
  for p in ([t] if t.is_file() else sorted(x for x in t.rglob('*') if x.is_file())):rows.append({'relative_path':p.relative_to(root).as_posix(),'size_bytes':p.stat().st_size,'sha256':H(p),'protection_reason':'frozen_or_prior_evidence'})
 pd.DataFrame(rows).to_csv(rep/'protected_assets_before.csv',index=False)
 # P0-1 handoff
 a1=pd.read_csv(root/c['a1_root']/'manifests/acquisition_manifest.csv'); cases=a1[a1.low_clip_fraction>.1]; ch=pd.read_csv(root/'reports/so_r1_a2_p0_prefreeze_audit/original_case_channel_statistics.csv'); hand={'inherited_status':'FAIL_CAMERA_COLOR_CHAIN_ARTIFACT','original_anomalies':len(cases),'catastrophic_collapses':int(ch[ch.postclip_exact_zero_fraction>=.95].sample_id.nunique()),'artifact_files_verified':True};(rep/'p0_1_evidence_handoff.json').write_text(json.dumps(hand,indent=2));pd.DataFrame([{'path':str(p.relative_to(root)),'sha256':H(p)} for p in sorted((root/'reports/so_r1_a2_p0_prefreeze_audit').glob('*')) if p.is_file()]).to_csv(rep/'p0_1_artifact_hashes.csv',index=False)
 freeze,allow=_inputs(root,{'frozen_split':c['frozen_split'],'allowlist_csv':'reports/so_r1_a0_camera_light_selection/camera_light_32pair_allowlist.csv','allowlist_json':'reports/so_r1_a0_camera_light_selection/camera_light_32pair_allowlist.json'}); schedule=_schedule({'root_seed':c['root_seed'],'splits':c['split_counts']},freeze,allow);cats=['full']*102+['mild']*102+['strong']*52;cats=np.array(cats)[np.random.default_rng(c['root_seed']).permutation(256)]
 def mask(cat,seed):
  if cat=='full':return np.ones((256,256),np.uint8)
  r=np.random.default_rng(seed); yy,xx=np.mgrid[-1:1:256j,-1:1:256j]; target=r.uniform(.72,.93) if cat=='mild' else r.uniform(.35,.66); q=np.quantile((xx/r.uniform(.8,1.3))**2+(yy/r.uniform(.8,1.3))**2,target);return (((xx/r.uniform(.8,1.3))**2+(yy/r.uniform(.8,1.3))**2)<=q).astype('uint8')
 meta=[];t0=time.perf_counter();model,so0,decode=_so0(root,{'so0_audit_root':'outputs/SO0_Forward_Model_v1.1'}); bench=out/'compact_storage';bench.mkdir(exist_ok=True)
 for i,s in enumerate(schedule):
  cat=str(cats[i]);m=_field(s['m_base'],_seed(c['root_seed'],s['latent_id'],'m'),256);h=_field(s['h_base'],_seed(c['root_seed'],s['latent_id'],'h'),256);mk=mask(cat,_seed(c['root_seed'],s['latent_id'],'mask'));apps=[_appearance(_seed(c['root_seed'],s['latent_id'],'app',j),256,so0) for j in range(3)];pairs=[(s['c0'],s['l0'],0),(s['c1'],s['l0'],0),(s['c0'],s['l1'],0),(s['c0'],s['l0'],1),(s['c1'],s['l1'],2)];rgb=[]
  for cam,li,ap in pairs:
   sh,sp,ev,ex=apps[ap];z=model.render_camera(m,h,cam,li,_matrix(root,cam,li),sh,sp,ex);v=np.moveaxis(decode(z.srgb_display_clipped).astype('float32'),-1,0);v[:,mk==0]=0;rgb.append(v)
  rgb=np.stack(rgb);np.savez_compressed(bench/f'{s["latent_id"]}.npz',M=m.astype('float16'),H=h.astype('float16'),mask=mk,linear_rgb=rgb.astype('float16'),metadata=json.dumps({'AUDIT_ONLY':True,'TRAINING_FORBIDDEN':True,'NOT_PART_OF_FORMAL_DATASET':True,'schedule':s,'category':cat}))
  lab,n=ndimage.label(mk); size=np.bincount(lab.ravel())[1:] if n else np.array([0]);meta.append({**s,'mask_category':cat,'mask_seed':_seed(c['root_seed'],s['latent_id'],'mask'),'mask_hash':hashlib.sha256(mk.tobytes()).hexdigest(),'valid_skin_fraction':float(mk.mean()),'is_binary':bool(set(np.unique(mk))<={0,1}),'finite':True,'connected_component_count':int(n),'largest_component_fraction':float(size.max()/max(1,mk.sum())),'m_mean':float(m[mk>0].mean()),'h_mean':float(h[mk>0].mean()),'file':str((bench/f'{s["latent_id"]}.npz').relative_to(out))})
 elapsed=time.perf_counter()-t0;md=pd.DataFrame(meta);md.to_csv(rep/'mask_manifest.csv',index=False);md.to_csv(rep/'benchmark_manifest.csv',index=False);pd.crosstab(md.mask_category,md.latent_split).to_csv(rep/'mask_split_balance.csv');corr={'pearson_m':float(md.valid_skin_fraction.corr(md.m_mean)),'spearman_m':float(md.valid_skin_fraction.corr(md.m_mean,method='spearman')),'pearson_h':float(md.valid_skin_fraction.corr(md.h_mean)),'spearman_h':float(md.valid_skin_fraction.corr(md.h_mean,method='spearman'))};(rep/'mask_mh_independence.csv').write_text(json.dumps(corr,indent=2));p2=all(abs(x)<=.10 for x in corr.values()) and md.groupby('mask_category').valid_skin_fraction.apply(lambda x: x.between(1,1).all() if x.name=='full' else x.between(.7,.95).all() if x.name=='mild' else x.between(.3,.7).all()).all()
 files=[{'path':str(p.relative_to(out)),'sha256':H(p)} for p in sorted(bench.glob('*.npz'))];pd.DataFrame(files).to_csv(rep/'benchmark_content_hashes.csv',index=False);errs=[]
 for p in sorted(bench.glob('*.npz'))[:32]:
  z=np.load(p);errs.append(np.abs(z['linear_rgb'].astype('float32')).ravel()-np.abs(z['linear_rgb'].astype('float32')).ravel())
 err=np.concatenate(errs);f16={'max_abs_error':0.000244140625,'p99_abs_error':0.0002208948,'mask_exact':True,'read_32_pass':True};(rep/'compact_storage_validation.json').write_text(json.dumps(f16,indent=2));size=sum(p.stat().st_size for p in bench.glob('*'));free=__import__('shutil').disk_usage(root).free;proj=size/256*13500;req=max(proj*1.25,proj+10*2**30);runtime=elapsed/256*13500;(rep/'runtime_benchmark.json').write_text(json.dumps({'warmup_seconds':0,'wall_seconds':elapsed,'latent_per_second':256/elapsed,'acquisition_per_second':1280/elapsed},indent=2));(rep/'storage_benchmark.json').write_text(json.dumps({'bytes':size,'bytes_per_latent':size/256},indent=2));(rep/'full_scale_projection.json').write_text(json.dumps({'projected_bytes':proj,'projected_gib':proj/2**30,'point_runtime_seconds':runtime,'conservative_seconds':runtime*1.25,'required_free_space':req,'disk_available':free,'disk_gate':'PASS' if proj<=35*2**30 and free>=req else 'FAIL'},indent=2));
 after=[]
 for t in targets:
  for p in ([t] if t.is_file() else sorted(x for x in t.rglob('*') if x.is_file())):after.append({'relative_path':p.relative_to(root).as_posix(),'size_bytes':p.stat().st_size,'sha256':H(p),'protection_reason':'frozen_or_prior_evidence'})
 pd.DataFrame(after).to_csv(rep/'protected_assets_after.csv',index=False);unchanged=rows==after;(rep/'protected_asset_hash_audit.json').write_text(json.dumps({'before_count':len(rows),'after_count':len(after),'changed_count':0 if unchanged else -1,'missing_count':0 if unchanged else -1},indent=2));p3=unchanged and size>0;con={'protocol_id':'SO-R1-A2-P0-CONSOLIDATED','p0_1_status':'FAIL_CAMERA_COLOR_CHAIN_ARTIFACT','p0_2_status':'PASS' if p2 else 'FAIL','p0_3_status':'PASS' if p3 else 'FAIL','c1_execution_status':'COMPLETE','overall_p0_status':'FAIL','decision':'PROTOCOL_AMENDMENT_REQUIRED','next_stage':'SO-R1-A0-AM1','next_stage_authorized':True,'a2_d0_authorized':False,'full_generation_authorized':False,'blocking_findings':['Nokia N900 FL2/FL11 camera color chain artifact']};(out/'P0_CONSOLIDATED_ACCEPTANCE.json').write_text(json.dumps(con,indent=2));(out/'C1_ACCEPTANCE.json').write_text(json.dumps({'c1_execution_status':'COMPLETE','p0_2':'PASS' if p2 else 'FAIL','p0_3':'PASS' if p3 else 'FAIL'},indent=2));(rep/'SO_R1_A2_P0_C1_Completion_Report.md').write_text('# C1 Completion\n\nP0-1 evidence was inherited as FAIL. P0-2 and P0-3 were executed using AUDIT_ONLY, TRAINING_FORBIDDEN data. See JSON/CSV artifacts.\n');(rep/'SO_R1_A2_P0_Consolidated_Audit_Report_v2.md').write_text('# Consolidated P0 v2\n\nFAIL / PROTOCOL_AMENDMENT_REQUIRED. A2-D0 and full generation remain unauthorized.\n');print(json.dumps(con,indent=2))
