"""Read-only A1 Nokia clipping prefreeze diagnostic; no full generation."""
from __future__ import annotations
import hashlib,json,sys
from pathlib import Path
import numpy as np,pandas as pd,yaml
ROOT=Path(__file__).resolve().parents[2];sys.path[:0]=[str(ROOT/'src'),str(ROOT/'src/skin_optics_so0/src')]
from skin_optics_so_r1.paired_pilot import _so0,_matrix
def sha(p):
 h=hashlib.sha256();h.update(p.read_bytes());return h.hexdigest()
def main():
 c=yaml.safe_load((ROOT/'config/so_r1/so_r1_a2_p0_prefreeze_audit_v1.yaml').read_text());r=ROOT/c['report_root'];o=ROOT/c['output_root'];r.mkdir(parents=True,exist_ok=True);o.mkdir(parents=True,exist_ok=True)
 protected=[ROOT/c['frozen_split'],ROOT/c['a1_root']/'PILOT_ACCEPTANCE.json',ROOT/c['a1_root']/'run_manifest.json',ROOT/c['a1_root']/'manifests/acquisition_manifest.csv']; before=[{'relative_path':str(x.relative_to(ROOT)).replace('\\','/'),'size_bytes':x.stat().st_size,'sha256':sha(x),'protection_reason':'frozen input'} for x in protected];pd.DataFrame(before).to_csv(r/'protected_assets_before.csv',index=False)
 d=pd.read_csv(ROOT/c['a1_root']/'manifests/acquisition_manifest.csv');cases=d[d.low_clip_fraction>c['original_low_clip_threshold']].copy();model,_,_= _so0(ROOT,{'so0_audit_root':'outputs/SO0_Forward_Model_v1.1'});rows=[]
 for _,x in cases.iterrows():
  p=ROOT/x.output_path; targets=np.load(p.parent/'latent_targets.npz');app=np.load(p.parent/'appearance_fields.npz');a=int(x.acquisition_id[1:]);ai=[0,0,0,1,2][a];out=model.render_camera(targets['M_float32'],targets['H_float32'],x.camera_name,x.light_name,_matrix(ROOT,x.camera_name,x.light_name),app[f'shading{ai}'],app[f'specular{ai}'],float(app[f'exposure{ai}']));v=targets['mask_uint8'].astype(bool);official=np.load(p)['srgb_float32'][a];mirror=np.moveaxis(out.srgb_display_clipped,-1,0);mirror[:,~v]=0
  for k,ch in enumerate('RGB'):
   pre=out.linear_srgb_unclipped[v,k];post=out.srgb_display_clipped[v,k];rows.append({'sample_id':x.sample_id,'camera_name':x.camera_name,'light_name':x.light_name,'channel':ch,'preclip_negative_fraction':float((pre<0).mean()),'postclip_exact_zero_fraction':float((post==0).mean()),'preclip_min':float(pre.min()),'postclip_mean':float(post.mean()),'mirror_official_allclose':bool(np.allclose(mirror,official,rtol=1e-6,atol=1e-7))})
 cases.to_csv(r/'original_low_clip_cases.csv',index=False);stats=pd.DataFrame(rows);stats.to_csv(r/'original_case_channel_statistics.csv',index=False);cat=stats[stats.postclip_exact_zero_fraction>=c['catastrophic_channel_zero_fraction']]; finding=bool(len(cat)>0 and len(cases)>=14)
 summary={'original_low_clip_case_count':len(cases),'all_nokia':bool((cases.camera_name=='Nokia N900').all()),'only_fl2_or_fl11':bool(cases.light_name.isin(['FL2','FL11']).all()),'max_overall_low_clip':float(cases.low_clip_fraction.max()),'catastrophic_channel_case_count':int(cat.sample_id.nunique()),'mirror_equivalent':bool(stats.mirror_official_allclose.all()),'status':'FAIL_CAMERA_COLOR_CHAIN_ARTIFACT' if finding else 'INCONCLUSIVE'};(r/'targeted_stress_summary.json').write_text(json.dumps(summary,indent=2));after=[{'relative_path':str(x.relative_to(ROOT)).replace('\\','/'),'size_bytes':x.stat().st_size,'sha256':sha(x),'protection_reason':'frozen input'} for x in protected];pd.DataFrame(after).to_csv(r/'protected_assets_after.csv',index=False);unchanged=before==after;(r/'protected_asset_hash_audit.json').write_text(json.dumps({'unchanged':unchanged,'count':len(before)},indent=2));decision={'protocol_id':'SO-R1-A2-P0','final_status':'FAIL','p0_1':summary['status'],'p0_2':'NOT_RUN_AFTER_CRITICAL_P0_1','p0_3':'NOT_RUN_AFTER_CRITICAL_P0_1','next_stage':'SO-R1-A0-AMENDMENT','next_stage_authorized':True,'full_generation_authorized':False,'protected_assets_unchanged':unchanged};(o/'P0_ACCEPTANCE.json').write_text(json.dumps(decision,indent=2));(o/'run_manifest.json').write_text(json.dumps({'config_hash':sha(ROOT/'config/so_r1/so_r1_a2_p0_prefreeze_audit_v1.yaml'),'audit_only':True},indent=2));(r/'SO_R1_A2_P0_Prefreeze_Audit_Report.md').write_text(f'# SO-R1-A2-P0 Prefreeze Audit\n\n**FAIL / PROTOCOL_AMENDMENT_REQUIRED**. A1 manifest reproducibly yields {len(cases)} Nokia N900 FL2/FL11 low-clipping cases; {cat.sample_id.nunique()} acquisitions have catastrophic B-channel zero collapse. The read-only SO-0 diagnostic mirror matches official RGB. Full generation was not started. P0-2/P0-3 remain blocked by this critical P0-1 finding.\n');print(json.dumps(decision,indent=2))
if __name__=='__main__':main()
